### ISSUE TITLE
failed to load Hadoop native library

### ISSUE THREAD

**Issue by chrisLeeTW** [smizy/docker-presto#1]
seems this docker image is not working on hive catalog,

due to failed to load Hadoop native library.

BR

Chris

**Comment by smizy** [comment]
@chrisLeeTW 
Would you show me the error log?

**Comment by chrisLeeTW** [comment]
@smizy 

log is here : https://gist.github.com/chrisLeeTW/b41ad5744e858ddc356a4222b362bd32

this is key infomation :

`presto_presto_coordinator | Caused by: java.lang.RuntimeException: failed to load Hadoop native library`

I already do the same research.

Found out that there is missing hadoop native library inside the docker images.

hope this info will help you out.

BR

Chris

**Comment by smizy** [comment]
@chrisLeeTW 
Thanks for information.
Though It is not easy to build hadoop native libraries on Alpine based system, I'll try it.

**Comment by smizy** [comment]
@chrisLeeTW 
I bundled alpine-built hadoop nativelib since smizy/presto:0.180-alpine. Please give it a try.

**Comment by chrisLeeTW** [comment]
@smizy a lot of thanks. I'll try it asap.

**Comment by chrisLeeTW** [comment]
@smizy really sorry for such delay reply.

I already tried. And It's successful to startup presto with hadoop.

nice work. I'll cose this.
