### ISSUE TITLE
When I log into the worker node presto cli doesn't work

### ISSUE THREAD

**Issue by mattroid** [smizy/docker-presto#3]
![image](https://user-images.githubusercontent.com/249426/50721170-c3913b00-106f-11e9-88f8-8c6c78d62ba4.png)

Looks like jansi is missing from the classpath. Maybe it's supposed to be packaged with presto?

**Comment by smizy** [comment]
@mattroid 
Thanks for reporting. I confirmed the jansi missing error. Adding alpine package java-jansi-native fixed the issue in my environment.
Please give it a try. (smizy/presto:0.215-alpine-r1).
